services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "3000:3000" # Expose the app on port 3000
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    networks:
      - chatbot-network
    restart: always
    volumes:
      - ./downloaded_media:/usr/src/app # Map the local directory to the container directory to make media files accesible

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379" # Expose Redis on port 6379
    networks:
      - chatbot-network
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres_server
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: whatsapp_messages
    ports:
      - "5432:5432" # Expose PostgreSQL on port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chatbot-network
    restart: always

volumes:
  postgres_data:

networks:
  chatbot-network:
    driver: bridge